[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=📡 ChatGPT,https://raw.githubusercontent.com/lxp1663/ClashRule/main/ChatGPT.list
ruleset=📡 ChatGPT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=📡 ChatGPT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=Ⓜ️ 必应,https://raw.githubusercontent.com/lxp1663/ClashRule/main/bing.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/lxp1663/ClashRule/main/GooglePlay.list
ruleset=⚡ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=RN,https://raw.githubusercontent.com/lxp1663/ClashRule/main/zijigwf.list
ruleset=REJECT,https://raw.githubusercontent.com/lxp1663/ClashRule/main/91weitu.list
ruleset=🗺 91卫图,https://raw.githubusercontent.com/lxp1663/ClashRule/main/91weitunew.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/lxp1663/ClashRule/main/zijiyuming.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎬 EMBY,https://raw.githubusercontent.com/Meilieage/webcdn/main/rule/list/Emby.list
ruleset=🎬 EMBY,https://raw.githubusercontent.com/lxp1663/ClashRule/main/emby.list
ruleset=🎬 EMBY,https://raw.githubusercontent.com/lxp1663/ClashRule/main/embyip.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]🚀 手动切换1`[]香港`[]♻️ 自动选择`[]机场`[]🚀 手动切换2`[]🚀 手动切换3`[]HY`[]ISIF`[]瓦工`[]GW`[]AZ`[]HY低倍率`[]日本`[]新加坡`[]美国`[]台湾`[]DIRECT
custom_proxy_group=🚀 手动切换1`select`.*
custom_proxy_group=🚀 手动切换2`select`.*
custom_proxy_group=🚀 手动切换3`select`.*
custom_proxy_group=📲 电报消息`select`[]新加坡`[]香港`[]🚀 手动切换1`[]🚀 手动切换2`[]HY`[]GW`[]ISIF`[]瓦工`[]HY低倍率`[]🚀 节点选择`[]AZ`[]♻️ 自动选择`[]日本`[]机场`[]🚀 手动切换3`[]美国`[]台湾`[]DIRECT
custom_proxy_group=🗺 91卫图`select`[]香港`[]机场`[]♻️ 自动选择`[]🚀 手动切换3`[]AZ`[]🚀 手动切换1`[]🚀 手动切换2`[]ISIF`[]瓦工`[]HY`[]🚀 节点选择`[]GW`[]日本`[]新加坡`[]美国`[]台湾`[]DIRECT
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]GW`[]香港`[]AZ`[]HY`[]日本`[]机场`[]🚀 手动切换1`[]🚀 手动切换2`[]🚀 手动切换3`[]新加坡`[]美国`[]台湾`[]DIRECT
custom_proxy_group=⚡ Speedtest`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]GW`[]香港`[]AZ`[]HY`[]日本`[]🚀 手动切换1`[]🚀 手动切换2`[]🚀 手动切换3`[]新加坡`[]美国`[]台湾`[]机场
custom_proxy_group=📡 ChatGPT`select`[]RN`[]美国`[]AZ`[]🚀 手动切换1`[]🚀 手动切换2`[]🚀 节点选择`[]♻️ 自动选择`[]GW`[]HY`[]🚀 手动切换3`[]香港`[]日本`[]新加坡`[]台湾`[]机场`[]DIRECT
custom_proxy_group=🎬 EMBY`select`[]HY低倍率`[]机场`[]香港`[]HY`[]GW`[]🚀 手动切换1`[]AZ`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择`[]新加坡`[]台湾`[]日本`[]🚀 手动切换2`[]🚀 手动切换3`
custom_proxy_group=Ⓜ️ 必应`select`[]RN`[]美国`[]AZ`[]HY`[]🚀 节点选择`[]香港``[]GW`[]日本`[]DIRECT`[]🚀 手动切换1`[]🚀 手动切换2`[]🚀 手动切换3`[]新加坡`[]台湾`[]机场
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择`[]GW`[]香港`[]AZ`[]HY`[]日本`[]🚀 手动切换1`[]🚀 手动切换2`[]🚀 手动切换3`[]新加坡`[]美国`[]台湾`[]机场
custom_proxy_group=♻️ 自动选择`url-test`(?=.*)^((?!(游戏流媒体)).)*$`http://cp.cloudflare.com/generate_204`300,,0
custom_proxy_group=机场`url-test`(?=.*(港|HK|(?i)Hong|日本|JP|Japan|新加坡|SG|(?i)Singapore|台|TW|Taiwan|Tai wan))^((?!(游戏流媒体|专用|日用|家宽|距离|冷门|套餐|cz|bz|ch|cc|cr|ws|ts|hy|ms|gcp|aws|ka|kb|kc|by|cw|bw|wb|-|])).)*$`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=AZ`url-test`(cz|bz)`http://cp.cloudflare.com/generate_204`300,,0
custom_proxy_group=GW`url-test`(?=.*(bw|rn|1663|wb|bz|cz))^((?!(游戏流媒体|华南|日用|家宽|Game|hy|game|Deutschland)).)*$`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=HY`url-test`(wb|rn|1663)`http://cp.cloudflare.com/generate_204`300,,0
custom_proxy_group=香港`url-test`(?=.*(港|HK|(?i)Hong))^((?!(游戏流媒体|华南|日用|家宽|Game|game|移动|高端|瓦工|-|])).)*$`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=日本`url-test`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(游戏流媒体|日用|家宽|瓦工|-|])).)*$`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=新加坡`url-test`(?=.*(新加坡|狮|獅|SG|(?i)Singapore))^((?!(更新|游戏流媒体|最新|日用|家宽|劫持|瓦工|大陆优化|移动|-|])).)*$`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=美国`url-test`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^((?!(专用|家宽|日用|瓦工|大陆优化|移动|-|])).)*$`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=台湾`url-test`(台|新北|彰化|TW|Taiwan|Tai wan)`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=ISIF`url-test`(isif|rfc)`http://cp.cloudflare.com/generate_204`300,,0
custom_proxy_group=瓦工`url-test`(?=.*(高端|瓦工|0.))^((?!(更新|游戏流媒体|最新|isif)).)*$`http://www.gstatic.com/generate_204`300,,0、
custom_proxy_group=HY低倍率`url-test`(wb)`http://cp.cloudflare.com/generate_204`300,,0
custom_proxy_group=BZ`url-test`(bz)`http://cp.cloudflare.com/generate_204`300,,0
custom_proxy_group=RN`url-test`(rn)`http://cp.cloudflare.com/generate_204`300,,0

;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
